#include "templ.h"
#include <iostream>
#include <exception>

using namespace std;


class exceptie1 : public exception{

    virtual const char* what() const throw(){

        return "Impartire la 0!";
    }

};

class exceptie2 : public exception{

    virtual const char* what() const throw(){

        return "Indexul este inafara domeniului!";
    }

};



int main(){

    int z=-1, x = 50, y = 0;

    int arr[4] = { 0 };

    int i = 10;

    exceptie1 divide0;

    exceptie2 index_out_of_bounds;



    try{

        if (y==0) throw divide0;

        z = x / y;

        cout << "Fara exceptie: z=" << z << endl;
    }
    catch (exception& e){

        cout << "Exceptie: " << e.what() << endl;
    }



    try{

        if (i > 3) throw index_out_of_bounds;

        arr[i] = z;

        for (i = 0; i < 4; i++)
            cout << "arr[" << i << "] = " << arr[i] << endl;
    }
    catch (exception& e){

        cout << "Exceptie: " << e.what() << endl;
    }


    return 0;

}